version: '3'
services:

  ### Nginx container ########Version:1.16.1#################################

  nginx:
      hostname: nginx
      build:
        context: work/components/nginx
        dockerfile: Dockerfile
      ports:
        - "${HTTP_PORT1}:80"
      volumes:
        - ${PROJECT_FOLDER}:/nginxapp
        - ./work/components/nginx/log:/var/log/nginx
      restart: always
      privileged: true
      networks:
        net-lnmp:
          ipv4_address: 10.127.1.2

  ### PHP container ###########Version:7.4.1##############################

  php:
      hostname: php
      build:
        context: work/components/php
        dockerfile: Dockerfile
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      volumes:
        - ${PROJECT_FOLDER}:/phpapp
        - ./work/components/php/log:/var/log
      restart: always
      privileged: true
      networks:
        net-lnmp:
          ipv4_address: 10.127.1.3


  ### Mysql container #########################################

  mariadb:
      hostname: mariadb
      image: harbor.nercoa.com/winjay/mariadb:10.4.11
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./work/components/mariadb/data:/var/lib/mysql
        - ./work/components/mariadb/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - ./work/components/mariadb/log:/var/log/mariadb
      restart: always
      privileged: true
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        net-lnmp:
          ipv4_address: 10.127.1.4

networks:
  net-lnmp:
    ipam:
      config:
        - subnet: 10.127.1.0/24